# fly.toml app configuration file generated for image-gen-bot on 2023-06-14T17:06:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "image-gen-bot"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
